[build]
builder = "nixpacks"
buildCommand = "yarn install && tsc -b && vite build"

[deploy]
healthCheckPath = "/ping"
restartPolicyMaxRetries = 10
startCommand = "yarn serve"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
