[build]
builder = "nixpacks"
buildCommand = "yarn install && tsc -b && vite build"

[deploy]
restartPolicyMaxRetries = 10
startCommand = "serve dist"
healthcheckPath = "/ping"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
